# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 286eaca55e3d6a62beb423a6406668f371cdcce052af8306e7329f0da5c548746aa0675d560ed9588f1634223a141bc28f55e2de6db7948d4f35cf9a9d1b6c10

test:
  secret_key_base: b2276ce59e4b7d288795e2fe54c848a3d55655e30b433336dc81d96f4314f3284a8e7838a8b6ed250f8197ed4aa0b92f8931c14c34a463ba88523cd7063394d4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
